from typing import Callable, Type

class raises:
    def __init__(self, ex: Type[BaseException]) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type, exc_info: BaseException, traceback) -> None: ...

def fixture(test: Callable) -> Callable: ...

import pytest.mark as mark
import pytest.config as config
