from typing import Callable

class skip:
    def __init__(self, test: Callable=None, reason: str=None) -> None: ...
    def __call__(self, test: Callable) -> Callable: ...

def skipif(condition: bool, reason: str=None) -> Callable[[Callable], Callable]: ...
