#!/usr/bin/env perl

use strict;

my $sigmoid = 300;
my $sentence = 20;
my $max_epoch = 5;

print "# Autogenerated file: do not modify!\n";

# Create a phony rule:
print "PHONY: models\n";
print "models:";
foreach my $dir ('f', 'b') {
    foreach my $fold (1..10) {
        print " \$(CORPUS).$dir-$sigmoid.$sentence.$fold.$max_epoch.h5";
    }
}
print "\n\n";

# Create rules for initial files.
foreach my $dir ('f', 'b') {
    foreach my $fold (1..10) {
        print "\$(CORPUS).$dir-$sigmoid.$sentence.$fold.1.h5: \$(ASSIGNED_VECTORS)\n";
        print "\t./train.py new --forwards --fold $fold \$<\n";
    }
}

print "\n";

# Create prefix rules for rest of the files.
foreach my $epoch (2..$max_epoch) {
    my $last_epoch = $epoch - 1;
    print "%.$epoch.h5: %.$last_epoch.h5\n";
    print "\t./train.py continue \$(ASSIGNED_VECTORS) \$<\n";
}
