#!/usr/bin/env perl

# Copyright 2017 Eddie Antonio Santos <easantos@ualberta.ca>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use strict;

my $sigmoid = 300;
my $sentence = 20;
my $max_epoch = 5;

print "# Autogenerated file: do not modify!\n";

# Create a phony rule:
print "PHONY: models\n";
print "models:";
foreach my $dir ('f', 'b') {
    foreach my $fold (1..10) {
        print " \$(CORPUS).$dir-$sigmoid.$sentence.$fold.$max_epoch.h5";
    }
}
print "\n\n";

# Create rules for initial files.
foreach my $direction ('forwards', 'backwards') {
    my $dir = substr $direction, 0, 1;
    foreach my $fold (1..10) {
        print "\$(CORPUS).$dir-$sigmoid.$sentence.$fold.1.h5: \$(ASSIGNED_VECTORS)\n";
        print "\t./train.py new --$direction --fold $fold \$<\n";
    }
}

print "\n";

# Create prefix rules for rest of the files.
foreach my $epoch (2..$max_epoch) {
    my $last_epoch = $epoch - 1;
    print "%.$epoch.h5: %.$last_epoch.h5\n";
    print "\t./train.py continue \$(ASSIGNED_VECTORS) \$<\n";
}
