#!/usr/bin/env perl

# Copyright 2017 Eddie Antonio Santos <easantos@ualberta.ca>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;

my $partitions = 5;  # Note: partitions are zero-indexed.
my $max_partition = $partitions - 1;
my $language = '$(LANGUAGE)';

print "# Autogenerated file: do not modify!\n";

# Create declare the phony rules.
print ".PHONY: models\n";

sub model_filename {
    my ($direction, $part) = @_;
    return "evaluation/$language/models/$language-$direction$part.hdf5";
}

# Create a phony rule for models.
print "models:";
foreach my $part (0 .. $max_partition) {
    foreach my $dir ('f', 'b') {
        print " @{[model_filename $dir, $part]}"
    }
}
print "\n";

# Create rules for the trained models
foreach my $direction ('forwards', 'backwards') {
    my $dir = substr $direction, 0, 1;
    foreach my $part (0 .. $max_partition) {
        print "@{[model_filename $dir, $part]}:\n";
        print "\ttrain -i $part --$direction ";
        print "--hidden-layers=\$(HIDDEN_LAYERS) ";
        print "--context-length=\$(CONTEXT)\n";
    }
}

###
print "\n";
###
