#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

"""
Loads the token lengths and produces a file with max length information.
"""

import numpy as np

template = """
'''
Autogenerated file! Do not modify!
'''

MINIMUM = {minimum!r}
MAXIMUM = {maximum!r}
MEDIAN = {median!r}
MEAN = {mean!r}
STDDEV = {stddev!r}
"""

if __name__ == '__main__':
    array = np.load('token_lengths.npy')
    array.sort()

    minimum = np.amin(array)
    maximum = np.amax(array)
    median = np.median(array)
    mean = np.mean(array)
    stddev = np.std(array)

    print(template.format(**locals()))
