#!/bin/sh

# Copyright 2017 Eddie Antonio Santos <easantos@ualberta.ca>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Wrapper script for train.py that runs it on a specific GPU depending on
# whether it's a forwards of backwards model.

GPU=

if [ "$1" = "new" ]; then
    case "$2" in
        --forwards)
            GPU=0
            ;;
        --backwards)
            GPU=1
            ;;
    esac
else
    case "$3" in
        *-f-*.h5)
            GPU=0
            ;;
        *-b-*.h5)
            GPU=1
            ;;
    esac
fi

if [ "$GPU" = "" ]; then
    echo "Could not determine GPU" >&2
    exit 1
fi

# Delegate to train.py
exec env THEANO_FLAGS='device=gpu'"$GPU" ./train.py $*
