from . import Strategy

def text() -> Strategy: ...
def lists(elements: Strategy=None, min_size: int=None, average_size: int=None, max_size: int=None, unique: True=False) -> Strategy: ...
def floats(min_value: float=None, max_value: float=None, allow_nan: bool=False, allow_infinity=None) -> Strategy: ...
def integers(min_value: int=None, max_value: int=None) -> Strategy: ...
