from typing import Union


class Redis:
    def lpush(self, name: Union[str, bytes], *values: Union[str, bytes]) -> None: ...
    def rpop(self, name: Union[str, bytes]) -> None: ...
    def delete(self, name: Union[str, bytes]) -> None: ...
    def brpoplpush(self, src: Union[str, bytes], dest: Union[str, bytes], timeout: int=None) -> bytes: ...

class StrictRedis(Redis):
    def __init__(self, db: int=None) -> None: ...
    def lrem(self, name: Union[str, bytes], count: int, value: Union[str, bytes]) -> None: ...
